// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250502181044_SeedContacts")]
    partial class SeedContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            IsFavorite = false,
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            ID = 2,
                            Email = "jane.smith@example.com",
                            FullName = "Jane Smith",
                            IsFavorite = false,
                            Phone = "234-567-8901"
                        },
                        new
                        {
                            ID = 3,
                            Email = "alice.johnson@example.com",
                            FullName = "Alice Johnson",
                            IsFavorite = false,
                            Phone = "345-678-9012"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
